### ISSUE TITLE
Error sending form with array

### ISSUE THREAD

**Issue by caiokawasaki** [Nevoss/form-wrapper-js#68]
I have a small problem when submitting a form that has an array. First I sent the form without being filled, then I filled it out and tried to send it again. The values `service_id` and `currency` are filled in correctly, however resending is not allowed due to the array.

This is my form:

```javascript
form: Form.create({
    service_id: null,
    currency: null,
    costs: [
		{
			value: null,
			starting_track: null,
			final_track: null
		},
		...
	]
})
```

![Screen Shot 2020-08-02 at 15 52 00](https://user-images.githubusercontent.com/9747004/89130120-cfa5de80-d4d8-11ea-9f85-da280322e439.png)

These are the errors returned from my API:

```json
{
   "message":"The given data was invalid.",
   "errors":{
      "service_id":[
         "The service id field is required."
      ],
      "currency":[
         "The currency field is required."
      ],
      "costs.0.value":[
         "The costs.0.value field is required."
      ],
      "costs.0.starting_track":[
         "The costs.0.starting_track field is required."
      ],
      "costs.0.final_track":[
         "The costs.0.final_track field is required."
      ]
   }
}
```

This is the error returned by the package:

![Screen Shot 2020-08-02 at 15 57 30](https://user-images.githubusercontent.com/9747004/89130130-e9dfbc80-d4d8-11ea-887f-c5307ba89971.png)

Somehow, he doesn't recognize that the inputs `costs.0.final_track`, `costs.0.starting_track` and `costs.0.value` have been filled.

How can I get around this situation?

**Comment by Nevoss** [comment]
Hey, based on your form it seems like there is no validation in it.

**Comment by caiokawasaki** [comment]
I'm not validating in front-end just in the back-end, for some reason `form-wrapper` is not removing errors from array...

**Comment by Nevoss** [comment]
Sorry man there is no support for array inputs.

**Comment by caiokawasaki** [comment]
Any plans for it? I could try to implement, but I'm not familiar with TS.

**Comment by Nevoss** [comment]
Tried it before, and it make a mess for simple forms, sorry man.
